import type { Track } from "@/types/music";

export const INITIAL_TRACKS: Track[] = [
  {
    id: "track-01",
    title: "Elegie",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 1,
    format: "FLAC",
    size: 30379582,
    sourceDriveId: "18B7wTjbf6YmeeLtzJNv2Etoqq5dyn6R5",
    audioUrl: "/api/drive?stream=original-v3&id=18B7wTjbf6YmeeLtzJNv2Etoqq5dyn6R5",
    artworkUrl: "/artwork/01.jpg",
    hasSyncedLyrics: false,
  },
  {
    id: "track-02",
    title: "IDK",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 2,
    format: "FLAC",
    size: 75523434,
    sourceDriveId: "1d6KPv_a2awhVvmimI_uLM-WtZEX1CI-Z",
    audioUrl: "/api/drive?stream=original-v3&id=1d6KPv_a2awhVvmimI_uLM-WtZEX1CI-Z",
    artworkUrl: "/artwork/02.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-03",
    title: "Wtf Bby I'm Lit",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 3,
    format: "FLAC",
    size: 62455274,
    sourceDriveId: "1K6Wj-NtZqLLSMD8GxCYIjeGDfzVhsP31",
    audioUrl: "/api/drive?stream=original-v3&id=1K6Wj-NtZqLLSMD8GxCYIjeGDfzVhsP31",
    artworkUrl: "/artwork/03.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-04",
    title: "Anh Không Muốn Nó Dễ Dàng",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 4,
    format: "FLAC",
    size: 65108805,
    sourceDriveId: "1lGApI1rGNDZbbch5tvvmZ0hKVrmBlP5l",
    audioUrl: "/api/drive?stream=original-v3&id=1lGApI1rGNDZbbch5tvvmZ0hKVrmBlP5l",
    artworkUrl: "/artwork/04.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-05",
    title: "Baby",
    artist: "RPT MCK feat. marzuz",
    album: "HVL",
    trackNumber: 5,
    format: "FLAC",
    size: 66434021,
    sourceDriveId: "1oaj87i7fiEEeEmCFvmnc-K3r90CoUZHL",
    audioUrl: "/api/drive?stream=original-v3&id=1oaj87i7fiEEeEmCFvmnc-K3r90CoUZHL",
    artworkUrl: "/artwork/05.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-06",
    title: "Yêu Anh Giết Anh",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 6,
    format: "FLAC",
    size: 62517851,
    sourceDriveId: "1X1Y1kxT55Sv2hvj5-pIzdNh2knFmJCZD",
    audioUrl: "/api/drive?stream=original-v3&id=1X1Y1kxT55Sv2hvj5-pIzdNh2knFmJCZD",
    artworkUrl: "/artwork/06.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-07",
    title: "Mắt Môi Tay Chân",
    artist: "RPT MCK feat. Tage",
    album: "HVL",
    trackNumber: 7,
    format: "FLAC",
    size: 72374098,
    sourceDriveId: "1kWv8qY3tK1srcd6gDVNBT0_Y4Yf8fOvx",
    audioUrl: "/api/drive?stream=original-v3&id=1kWv8qY3tK1srcd6gDVNBT0_Y4Yf8fOvx",
    artworkUrl: "/artwork/07.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-08",
    title: "Đao Của Anh Vừa",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 8,
    format: "FLAC",
    size: 48187111,
    sourceDriveId: "1O70xU-CPQcRhbV7nTAdG68F9MbRquO36",
    audioUrl: "/api/drive?stream=original-v3&id=1O70xU-CPQcRhbV7nTAdG68F9MbRquO36",
    artworkUrl: "/artwork/08.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-09",
    title: "Là Gì Của Nhau",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 9,
    format: "FLAC",
    size: 51592565,
    sourceDriveId: "1O5x3tCwRsyqY5BLUhI0CFDQZQaVsfIp_",
    audioUrl: "/api/drive?stream=original-v3&id=1O5x3tCwRsyqY5BLUhI0CFDQZQaVsfIp_",
    artworkUrl: "/artwork/09.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-10",
    title: "Night In Prague",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 10,
    format: "FLAC",
    size: 78563687,
    sourceDriveId: "1sgaZKgGysGebYWvIGCGT2G6F7Qf0671u",
    audioUrl: "/api/drive?stream=original-v3&id=1sgaZKgGysGebYWvIGCGT2G6F7Qf0671u",
    artworkUrl: "/artwork/10.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-11",
    title: "Một Cái Ôm",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 11,
    format: "FLAC",
    size: 65446972,
    sourceDriveId: "1JeACb1D5FBiB3ROInjWEQDy9Vd62rzd5",
    audioUrl: "/api/drive?stream=original-v3&id=1JeACb1D5FBiB3ROInjWEQDy9Vd62rzd5",
    artworkUrl: "/artwork/11.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-12",
    title: "Liệm",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 12,
    format: "FLAC",
    size: 90835362,
    sourceDriveId: "1lc6W3Go9ybXLGhYNGAFN-_ob64MflVVL",
    audioUrl: "/api/drive?stream=original-v3&id=1lc6W3Go9ybXLGhYNGAFN-_ob64MflVVL",
    artworkUrl: "/artwork/12.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-13",
    title: "Nếu Như Ta Chẳng Còn",
    artist: "RPT MCK feat. A$AP Ướt Mi",
    album: "HVL",
    trackNumber: 13,
    format: "FLAC",
    size: 116995739,
    sourceDriveId: "13tdU4ChHgkDSkjHV87aqLZyPKIeWiun-",
    audioUrl: "/api/drive?stream=original-v3&id=13tdU4ChHgkDSkjHV87aqLZyPKIeWiun-",
    artworkUrl: "/artwork/13.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-14",
    title: "Ai Mới Là Kẻ Xấu Xa",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 14,
    format: "FLAC",
    size: 77945681,
    sourceDriveId: "1KM8BG-8dAm4Q30bJ52UR5UwfDQ5si_bJ",
    audioUrl: "/api/drive?stream=original-v3&id=1KM8BG-8dAm4Q30bJ52UR5UwfDQ5si_bJ",
    artworkUrl: "/artwork/14.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-15",
    title: "Slippery",
    artist: "RPT MCK feat. Tùng Dương",
    album: "HVL",
    trackNumber: 15,
    format: "FLAC",
    size: 89012975,
    sourceDriveId: "1p098x-nFu79GWTAvA5Z59fjHDY2CDH-X",
    audioUrl: "/api/drive?stream=original-v3&id=1p098x-nFu79GWTAvA5Z59fjHDY2CDH-X",
    artworkUrl: "/artwork/15.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-16",
    title: "Intenpol",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 16,
    format: "FLAC",
    size: 23025982,
    sourceDriveId: "1T-XKDC9j9OTzMnVJlTGlZ3XEiOxubMCy",
    audioUrl: "/api/drive?stream=original-v3&id=1T-XKDC9j9OTzMnVJlTGlZ3XEiOxubMCy",
    artworkUrl: "/artwork/16.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-17",
    title: "Tây Thi",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 17,
    format: "FLAC",
    size: 42739607,
    sourceDriveId: "1_purQHSHrB_2VikgoxlM1jHMheAqsvN0",
    audioUrl: "/api/drive?stream=original-v3&id=1_purQHSHrB_2VikgoxlM1jHMheAqsvN0",
    artworkUrl: "/artwork/17.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-18",
    title: "Hút và Hút",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 18,
    format: "FLAC",
    size: 54178193,
    sourceDriveId: "1dFbzyQF-cbNIsahJFGxoBQUA-Wqkn7u6",
    audioUrl: "/api/drive?stream=original-v3&id=1dFbzyQF-cbNIsahJFGxoBQUA-Wqkn7u6",
    artworkUrl: "/artwork/18.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-19",
    title: "Dưa Chua",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 19,
    format: "FLAC",
    size: 71208489,
    sourceDriveId: "178thNTHBYs4NoQr6dwiIqmRlTuK2RM1e",
    audioUrl: "/api/drive?stream=original-v3&id=178thNTHBYs4NoQr6dwiIqmRlTuK2RM1e",
    artworkUrl: "/artwork/19.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-20",
    title: "Xa Xôi",
    artist: "RPT MCK feat. Obito",
    album: "HVL",
    trackNumber: 20,
    format: "FLAC",
    size: 83790468,
    sourceDriveId: "1m6d-S7RSbse4Er3ZF_vZMLmEUBLAxWhL",
    audioUrl: "/api/drive?stream=original-v3&id=1m6d-S7RSbse4Er3ZF_vZMLmEUBLAxWhL",
    artworkUrl: "/artwork/20.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-21",
    title: "Che Phủ",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 21,
    format: "FLAC",
    size: 60252257,
    sourceDriveId: "1TcFn90c3uEtL-UAf1xkJylKdXqkcnnbz",
    audioUrl: "/api/drive?stream=original-v3&id=1TcFn90c3uEtL-UAf1xkJylKdXqkcnnbz",
    artworkUrl: "/artwork/21.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-22",
    title: "Oanh M = Thuoc",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 22,
    format: "FLAC",
    size: 79752274,
    sourceDriveId: "1j61Mco96veNwJz1JypcLJYnd3ImgJ0ik",
    audioUrl: "/api/drive?stream=original-v3&id=1j61Mco96veNwJz1JypcLJYnd3ImgJ0ik",
    artworkUrl: "/artwork/22.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-23",
    title: "Ghet Xog Lai Thik",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 23,
    format: "FLAC",
    size: 50278961,
    sourceDriveId: "1XUqfhsR1yCkRQCNUkFjUmzizKbukBNaP",
    audioUrl: "/api/drive?stream=original-v3&id=1XUqfhsR1yCkRQCNUkFjUmzizKbukBNaP",
    artworkUrl: "/artwork/23.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-24",
    title: "Nhìn Kẻ Thù Của Tao",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 24,
    format: "FLAC",
    size: 90706418,
    sourceDriveId: "1JPJzJBENfPILgEZqP2pMYeNni1VQPQIR",
    audioUrl: "/api/drive?stream=original-v3&id=1JPJzJBENfPILgEZqP2pMYeNni1VQPQIR",
    artworkUrl: "/artwork/24.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-25",
    title: "Envy",
    artist: "RPT MCK feat. THANHDRAW",
    album: "HVL",
    trackNumber: 25,
    format: "FLAC",
    size: 90218850,
    sourceDriveId: "1LGDP3qTNk3mBEUKXsEqY9SExQsxSHvH7",
    audioUrl: "/api/drive?stream=original-v3&id=1LGDP3qTNk3mBEUKXsEqY9SExQsxSHvH7",
    artworkUrl: "/artwork/25.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-26",
    title: "Cảm Ơn",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 26,
    format: "FLAC",
    size: 51784858,
    sourceDriveId: "155WGcZ7AzD4TavEjvXV8vyux9-ITDhWW",
    audioUrl: "/api/drive?stream=original-v3&id=155WGcZ7AzD4TavEjvXV8vyux9-ITDhWW",
    artworkUrl: "/artwork/26.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-27",
    title: "Không Cần Lo Cho Tao",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 27,
    format: "FLAC",
    size: 63918584,
    sourceDriveId: "1Kv_Z--xAUHlzX0Ui_eMPCrPuq2lZtRP7",
    audioUrl: "/api/drive?stream=original-v3&id=1Kv_Z--xAUHlzX0Ui_eMPCrPuq2lZtRP7",
    artworkUrl: "/artwork/27.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-28",
    title: "Huh",
    artist: "RPT MCK feat. RPT Orijinn & THANHDRAW",
    album: "HVL",
    trackNumber: 28,
    format: "FLAC",
    size: 97542998,
    sourceDriveId: "1rYnKEYchuOill5A4wElid3zZY-UI1yEw",
    audioUrl: "/api/drive?stream=original-v3&id=1rYnKEYchuOill5A4wElid3zZY-UI1yEw",
    artworkUrl: "/artwork/28.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-29",
    title: "Nguyễn Văn Mười",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 29,
    format: "FLAC",
    size: 77174193,
    sourceDriveId: "1T9z5rVG6KB2gF44MGDWeLLUOddM45tVd",
    audioUrl: "/api/drive?stream=original-v3&id=1T9z5rVG6KB2gF44MGDWeLLUOddM45tVd",
    artworkUrl: "/artwork/29.jpg",
    hasSyncedLyrics: true,
  },
  {
    id: "track-30",
    title: "Thịt Lợn",
    artist: "RPT MCK",
    album: "HVL",
    trackNumber: 30,
    format: "FLAC",
    size: 90422264,
    sourceDriveId: "1MWwN6KZ9cA1JQRWFvYwxJpQxnjSDjvyc",
    audioUrl: "/api/drive?stream=original-v3&id=1MWwN6KZ9cA1JQRWFvYwxJpQxnjSDjvyc",
    artworkUrl: "/artwork/30.jpg",
    hasSyncedLyrics: true,
  },
];
